In [2]:
import pandas as pd

In [3]:
df=pd.read_excel('/content/Sample_AI_dataset.xlsx')

**merge, concat and join
conditional filters in pandas
rename and replace in pandas
convert lowercase to upper, uppercase to lower in pandas**

In [5]:
'''
head
describe
info
how is the data
'''

'\nhead\ndescribe\ninfo\nhow is the data\n'

In [6]:
df.head()

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10,AI impact level
0,0.382,63514,0.830,0.0406,0.0348,52,6.4,Low
1,0.608,63514,0.817,0.0517,0.0423,39,6.5,Medium
2,0.198,63514,0.816,0.0176,0.0168,37,6.8,Low
3,0.720,63514,0.818,0.0924,0.0642,50,6.8,High
4,0.676,63514,0.828,0.0667,0.0374,37,6.2,Medium

In [7]:
df.tail()

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10,AI impact level
14,0.750,63263,0.825,0.0746,0.0463,49,6.0,Medium
15,0.278,63263,0.814,0.0220,0.0138,46,6.5,Low
16,0.715,63263,0.830,0.0825,0.0459,48,7.1,High
17,0.557,63263,0.806,0.0624,0.0381,43,5.9,Medium
18,0.797,63263,0.832,0.0932,0.0632,40,6.1,High

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   sector_automation_risk_score            19 non-null     float64
 1   gdp_per_capita_usd                      19 non-null     int64
 2   ai_adoption_index                       19 non-null     float64
 3   pct_sector_workforce_displaced          19 non-null     float64
 4   pct_sector_workforce_new_roles_created  19 non-null     float64
 5   reskilling_programs_count               19 non-null     int64
 6   govt_ai_policy_score_1_to_10            19 non-null     float64
 7   AI impact level                         19 non-null     object
dtypes: float64(5), int64(2), object(1)
memory usage: 1.3+ KB

In [9]:
df.describe()

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,0.548947,63395.105263,0.822842,0.058063,0.041826,45.736842,6.605263
std,0.206219,128.760283,0.011266,0.026342,0.018919,5.743035,0.396476
min,0.198000,63263.000000,0.805000,0.017600,0.011800,37.000000,5.900000
25%,0.375000,63263.000000,0.816500,0.039800,0.029250,40.000000,6.400000
50%,0.608000,63514.000000,0.821000,0.062400,0.041600,47.000000,6.600000
75%,0.717500,63514.000000,0.830000,0.073750,0.058100,51.000000,6.800000
max,0.797000,63514.000000,0.848000,0.104400,0.073600,53.000000,7.300000

In [10]:
df.columns

Index(['sector_automation_risk_score', 'gdp_per_capita_usd',
       'ai_adoption_index', 'pct_sector_workforce_displaced',
       'pct_sector_workforce_new_roles_created', 'reskilling_programs_count',
       'govt_ai_policy_score_1_to_10', 'AI impact level'],
      dtype='object')

In [11]:
df.shape

(19, 8)

In [12]:
df.isnull().sum()

sector_automation_risk_score              0
gdp_per_capita_usd                        0
ai_adoption_index                         0
pct_sector_workforce_displaced            0
pct_sector_workforce_new_roles_created    0
reskilling_programs_count                 0
govt_ai_policy_score_1_to_10              0
AI impact level                           0
dtype: int64

In [13]:
#find the unique values in a single column
df['govt_ai_policy_score_1_to_10'].unique()

array([6.4, 6.5, 6.8, 6.2, 6.7, 6.6, 7.3, 6.9, 6. , 7.1, 5.9, 6.1])

In [14]:
df['govt_ai_policy_score_1_to_10'].nunique()

12

In [15]:
#conditional search
df[df["govt_ai_policy_score_1_to_10"]>6.5]

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10,AI impact level
2,0.198,63514,0.816,0.0176,0.0168,37,6.8,Low
3,0.720,63514,0.818,0.0924,0.0642,50,6.8,High
5,0.287,63514,0.822,0.0290,0.0237,39,6.7,Low
8,0.793,63514,0.819,0.1044,0.0736,53,6.6,High
9,0.443,63514,0.805,0.0390,0.0216,53,7.3,Medium
10,0.368,63263,0.821,0.0434,0.0353,43,7.3,Low
11,0.638,63263,0.820,0.0729,0.0668,47,6.9,Medium
12,0.205,63263,0.830,0.0176,0.0118,52,6.7,Low
13,0.756,63263,0.848,0.0712,0.0530,49,6.8,Medium
16,0.715,63263,0.830,0.0825,0.0459,48,7.1,High

**merge, concat and join**

In [16]:
a=df.head(5)
b=df.tail(5)
#vertical concat
c=pd.concat([a,b],axis=0)
c

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10,AI impact level
0,0.382,63514,0.830,0.0406,0.0348,52,6.4,Low
1,0.608,63514,0.817,0.0517,0.0423,39,6.5,Medium
2,0.198,63514,0.816,0.0176,0.0168,37,6.8,Low
3,0.720,63514,0.818,0.0924,0.0642,50,6.8,High
4,0.676,63514,0.828,0.0667,0.0374,37,6.2,Medium
14,0.750,63263,0.825,0.0746,0.0463,49,6.0,Medium
15,0.278,63263,0.814,0.0220,0.0138,46,6.5,Low
16,0.715,63263,0.830,0.0825,0.0459,48,7.1,High
17,0.557,63263,0.806,0.0624,0.0381,43,5.9,Medium
18,0.797,63263,0.832,0.0932,0.0632,40,6.1,High

In [17]:
#horizontal concat
d=pd.concat([a,b],axis=1)
d

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10,AI impact level,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10,AI impact level
0,0.382,63514.0,0.830,0.0406,0.0348,52.0,6.4,Low,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.608,63514.0,0.817,0.0517,0.0423,39.0,6.5,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.198,63514.0,0.816,0.0176,0.0168,37.0,6.8,Low,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.720,63514.0,0.818,0.0924,0.0642,50.0,6.8,High,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.676,63514.0,0.828,0.0667,0.0374,37.0,6.2,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.750,63263.0,0.825,0.0746,0.0463,49.0,6.0,Medium
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.278,63263.0,0.814,0.0220,0.0138,46.0,6.5,Low
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.715,63263.0,0.830,0.0825,0.0459,48.0,7.1,High
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.557,63263.0,0.806,0.0624,0.0381,43.0,5.9,Medium
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.797,63263.0,0.832,0.0932,0.0632,40.0,6.1,High

In [18]:
#merge
df.head()

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10,AI impact level
0,0.382,63514,0.830,0.0406,0.0348,52,6.4,Low
1,0.608,63514,0.817,0.0517,0.0423,39,6.5,Medium
2,0.198,63514,0.816,0.0176,0.0168,37,6.8,Low
3,0.720,63514,0.818,0.0924,0.0642,50,6.8,High
4,0.676,63514,0.828,0.0667,0.0374,37,6.2,Medium

In [19]:
a=df.loc[1:10,'sector_automation_risk_score':'govt_ai_policy_score_1_to_10']
b=df.loc[5:15,'sector_automation_risk_score':'govt_ai_policy_score_1_to_10']

In [20]:
a

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10
1,0.608,63514,0.817,0.0517,0.0423,39,6.5
2,0.198,63514,0.816,0.0176,0.0168,37,6.8
3,0.720,63514,0.818,0.0924,0.0642,50,6.8
4,0.676,63514,0.828,0.0667,0.0374,37,6.2
5,0.287,63514,0.822,0.0290,0.0237,39,6.7
6,0.694,63514,0.810,0.0713,0.0645,40,6.4
7,0.565,63514,0.843,0.0507,0.0416,52,6.5
8,0.793,63514,0.819,0.1044,0.0736,53,6.6
9,0.443,63514,0.805,0.0390,0.0216,53,7.3
10,0.368,63263,0.821,0.0434,0.0353,43,7.3

In [21]:
b.merge(a)

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10
0,0.287,63514,0.822,0.0290,0.0237,39,6.7
1,0.694,63514,0.810,0.0713,0.0645,40,6.4
2,0.565,63514,0.843,0.0507,0.0416,52,6.5
3,0.793,63514,0.819,0.1044,0.0736,53,6.6
4,0.443,63514,0.805,0.0390,0.0216,53,7.3
5,0.368,63263,0.821,0.0434,0.0353,43,7.3

**loc and iloc**

In [22]:
a.loc[5:10]

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10
5,0.287,63514,0.822,0.0290,0.0237,39,6.7
6,0.694,63514,0.810,0.0713,0.0645,40,6.4
7,0.565,63514,0.843,0.0507,0.0416,52,6.5
8,0.793,63514,0.819,0.1044,0.0736,53,6.6
9,0.443,63514,0.805,0.0390,0.0216,53,7.3
10,0.368,63263,0.821,0.0434,0.0353,43,7.3

In [23]:
b.loc[5:10]

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10
5,0.287,63514,0.822,0.0290,0.0237,39,6.7
6,0.694,63514,0.810,0.0713,0.0645,40,6.4
7,0.565,63514,0.843,0.0507,0.0416,52,6.5
8,0.793,63514,0.819,0.1044,0.0736,53,6.6
9,0.443,63514,0.805,0.0390,0.0216,53,7.3
10,0.368,63263,0.821,0.0434,0.0353,43,7.3

In [24]:
df.iloc[0:5,1:10]

,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10,AI impact level
0,63514,0.830,0.0406,0.0348,52,6.4,Low
1,63514,0.817,0.0517,0.0423,39,6.5,Medium
2,63514,0.816,0.0176,0.0168,37,6.8,Low
3,63514,0.818,0.0924,0.0642,50,6.8,High
4,63514,0.828,0.0667,0.0374,37,6.2,Medium

**join**

In [25]:
'''
sample example for join
'''

students = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie']},
    index=['S01', 'S02', 'S03']
)


scores = pd.DataFrame({
    'Math': [95, 80],
    'Science': [88, 92]},
    index=['S01', 'S02']
)

result = students.join(scores)
result

        Name  Math  Science
S01    Alice  95.0     88.0
S02      Bob  80.0     92.0
S03  Charlie   NaN      NaN

In [26]:
df1=df.iloc[1:10,0:3]
df2=df.iloc[15:20,4:6]

In [27]:
gg=df1.join(df2)
gg

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_new_roles_created,reskilling_programs_count
1,0.608,63514,0.817,NaN,NaN
2,0.198,63514,0.816,NaN,NaN
3,0.720,63514,0.818,NaN,NaN
4,0.676,63514,0.828,NaN,NaN
5,0.287,63514,0.822,NaN,NaN
6,0.694,63514,0.810,NaN,NaN
7,0.565,63514,0.843,NaN,NaN
8,0.793,63514,0.819,NaN,NaN
9,0.443,63514,0.805,NaN,NaN

In [28]:
df1

   sector_automation_risk_score  gdp_per_capita_usd  ai_adoption_index
1                         0.608               63514              0.817
2                         0.198               63514              0.816
3                         0.720               63514              0.818
4                         0.676               63514              0.828
5                         0.287               63514              0.822
6                         0.694               63514              0.810
7                         0.565               63514              0.843
8                         0.793               63514              0.819
9                         0.443               63514              0.805

In [29]:
df2

    pct_sector_workforce_new_roles_created  reskilling_programs_count
15                                  0.0138                         46
16                                  0.0459                         48
17                                  0.0381                         43
18                                  0.0632                         40

In [30]:


# Left Table (df1)
df1 = pd.DataFrame({'A': ['A1', 'A2', 'A3']}, index=[1, 2, 3])

# Right Table (df2)
df2 = pd.DataFrame({'B': ['B3', 'B4', 'B5']}, index=[3, 4, 5])

# How to apply them:
inner_res = df1.join(df2, how='inner') # Only Index 3
left_res  = df1.join(df2, how='left')  # Indices 1, 2, 3
right_res = df1.join(df2, how='right') # Indices 3, 4, 5

In [31]:
inner_res

    A   B
3  A3  B3

In [32]:
left_res

    A    B
1  A1  NaN
2  A2  NaN
3  A3   B3

In [33]:
right_res

     A   B
3   A3  B3
4  NaN  B4
5  NaN  B5

'\ngroupby function- mean, median, standard deviation\ncreate a dataframe\ndrop and fill\nsort_values\nsize\ninsert, delete, assign, replace\n'


1. groupby function- mean, median, standard deviation
2. create a dataframe
3. drop and fill
4. sort_values
5. size
6. insert, delete, assign, replace

In [35]:
elakkiya= {
    'Name':['Yadu','Rithu', 'Elakkiya','Muth'],
    'Marks':[99,99,95, 97]
}
dat=pd.DataFrame(elakkiya)
dat

       Name  Marks
0      Yadu     99
1     Rithu     99
2  Elakkiya     95
3      Muth     97

In [36]:
dat=pd.DataFrame({
    'Name':['Yadu','Rithu', 'Elakkiya','Muth'],
    'Marks':[99,99,95, 97]
})
dat

       Name  Marks
0      Yadu     99
1     Rithu     99
2  Elakkiya     95
3      Muth     97

In [38]:
gg=df.groupby('pct_sector_workforce_displaced')['pct_sector_workforce_displaced'].mean()

In [39]:
gg

pct_sector_workforce_displaced
0.0176    0.0176
0.0220    0.0220
0.0290    0.0290
0.0390    0.0390
0.0406    0.0406
0.0434    0.0434
0.0507    0.0507
0.0517    0.0517
0.0624    0.0624
0.0667    0.0667
0.0712    0.0712
0.0713    0.0713
0.0729    0.0729
0.0746    0.0746
0.0825    0.0825
0.0924    0.0924
0.0932    0.0932
0.1044    0.1044
Name: pct_sector_workforce_displaced, dtype: float64

In [40]:
g1=df.groupby('pct_sector_workforce_new_roles_created')['pct_sector_workforce_new_roles_created'].std()
g1

pct_sector_workforce_new_roles_created
0.0118   NaN
0.0138   NaN
0.0168   NaN
0.0216   NaN
0.0237   NaN
0.0348   NaN
0.0353   NaN
0.0374   NaN
0.0381   NaN
0.0416   NaN
0.0423   NaN
0.0459   NaN
0.0463   NaN
0.0530   NaN
0.0632   NaN
0.0642   NaN
0.0645   NaN
0.0668   NaN
0.0736   NaN
Name: pct_sector_workforce_new_roles_created, dtype: float64

In [41]:
g2=df.groupby('pct_sector_workforce_new_roles_created')['pct_sector_workforce_new_roles_created'].median()
g2

pct_sector_workforce_new_roles_created
0.0118    0.0118
0.0138    0.0138
0.0168    0.0168
0.0216    0.0216
0.0237    0.0237
0.0348    0.0348
0.0353    0.0353
0.0374    0.0374
0.0381    0.0381
0.0416    0.0416
0.0423    0.0423
0.0459    0.0459
0.0463    0.0463
0.0530    0.0530
0.0632    0.0632
0.0642    0.0642
0.0645    0.0645
0.0668    0.0668
0.0736    0.0736
Name: pct_sector_workforce_new_roles_created, dtype: float64

In [42]:
g3=df.groupby('pct_sector_workforce_new_roles_created')['pct_sector_workforce_new_roles_created'].size()
g3

pct_sector_workforce_new_roles_created
0.0118    1
0.0138    1
0.0168    1
0.0216    1
0.0237    1
0.0348    1
0.0353    1
0.0374    1
0.0381    1
0.0416    1
0.0423    1
0.0459    1
0.0463    1
0.0530    1
0.0632    1
0.0642    1
0.0645    1
0.0668    1
0.0736    1
Name: pct_sector_workforce_new_roles_created, dtype: int64

In [43]:
df.columns

Index(['sector_automation_risk_score', 'gdp_per_capita_usd',
       'ai_adoption_index', 'pct_sector_workforce_displaced',
       'pct_sector_workforce_new_roles_created', 'reskilling_programs_count',
       'govt_ai_policy_score_1_to_10', 'AI impact level'],
      dtype='object')

In [44]:
data=df.drop(columns={'AI impact level'})
data

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10
0,0.382,63514,0.830,0.0406,0.0348,52,6.4
1,0.608,63514,0.817,0.0517,0.0423,39,6.5
2,0.198,63514,0.816,0.0176,0.0168,37,6.8
3,0.720,63514,0.818,0.0924,0.0642,50,6.8
4,0.676,63514,0.828,0.0667,0.0374,37,6.2
5,0.287,63514,0.822,0.0290,0.0237,39,6.7
6,0.694,63514,0.810,0.0713,0.0645,40,6.4
7,0.565,63514,0.843,0.0507,0.0416,52,6.5
8,0.793,63514,0.819,0.1044,0.0736,53,6.6
9,0.443,63514,0.805,0.0390,0.0216,53,7.3
10,0.368,63263,0.821,0.0434,0.0353,43,7.3
11,0.638,63263,0.820,0.0729,0.0668,47,6.9
12,0.205,63263,0.830,0.0176,0.0118,52,6.7
13,0.756,63263,0.848,0.0712,0.0530,49,6.8
14,0.750,63263,0.825,0.0746,0.0463,49,6.0
15,0.278,63263,0.814,0.0220,0.0138,46,6.5
16,0.715,63263,0.830,0.0825,0.0459,48,7.1
17,0.557,63263,0.806,0.0624,0.0381,43,5.9
18,0.797,63263,0.832,0.0932,0.0632,40,6.1

**fill**

In [45]:
import numpy as np
# Creating a sample dataframe with missing values
data = {
    'Name': ['Yadu', 'Rithu', 'Elakkiya', 'Muth'],
    'Score': [99, np.nan, 95, np.nan],
    'City': ['Chennai', 'Bangalore', np.nan, 'Chennai']
}
df_sample = pd.DataFrame(data)

# Fill all NaN values with 0
df_filled = df_sample.fillna(0)
print(df_filled)

       Name  Score       City
0      Yadu   99.0    Chennai
1     Rithu    0.0  Bangalore
2  Elakkiya   95.0          0
3      Muth    0.0    Chennai

In [46]:
# Sort by a single column (Ascending)
df.sort_values(by='sector_automation_risk_score')

,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10,AI impact level
2,0.198,63514,0.816,0.0176,0.0168,37,6.8,Low
12,0.205,63263,0.830,0.0176,0.0118,52,6.7,Low
15,0.278,63263,0.814,0.0220,0.0138,46,6.5,Low
5,0.287,63514,0.822,0.0290,0.0237,39,6.7,Low
10,0.368,63263,0.821,0.0434,0.0353,43,7.3,Low
0,0.382,63514,0.830,0.0406,0.0348,52,6.4,Low
9,0.443,63514,0.805,0.0390,0.0216,53,7.3,Medium
17,0.557,63263,0.806,0.0624,0.0381,43,5.9,Medium
7,0.565,63514,0.843,0.0507,0.0416,52,6.5,Medium
1,0.608,63514,0.817,0.0517,0.0423,39,6.5,Medium
11,0.638,63263,0.820,0.0729,0.0668,47,6.9,Medium
4,0.676,63514,0.828,0.0667,0.0374,37,6.2,Medium
6,0.694,63514,0.810,0.0713,0.0645,40,6.4,Medium
16,0.715,63263,0.830,0.0825,0.0459,48,7.1,High
3,0.720,63514,0.818,0.0924,0.0642,50,6.8,High
14,0.750,63263,0.825,0.0746,0.0463,49,6.0,Medium
13,0.756,63263,0.848,0.0712,0.0530,49,6.8,Medium
8,0.793,63514,0.819,0.1044,0.0736,53,6.6,High
18,0.797,63263,0.832,0.0932,0.0632,40,6.1,High

In [47]:
df.size

152

In [51]:
# Insert a 'Country' column at the very beginning (index 0)
da1=df.copy()
da1.insert(0,'region','Global')
da1.head()

,region,Country,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,reskilling_programs_count,govt_ai_policy_score_1_to_10,AI impact level
0,Global,Global,0.382,63514,0.830,0.0406,0.0348,52,6.4,Low
1,Global,Global,0.608,63514,0.817,0.0517,0.0423,39,6.5,Medium
2,Global,Global,0.198,63514,0.816,0.0176,0.0168,37,6.8,Low
3,Global,Global,0.720,63514,0.818,0.0924,0.0642,50,6.8,High
4,Global,Global,0.676,63514,0.828,0.0667,0.0374,37,6.2,Medium

In [53]:
# Replace specific text values
da1['AI impact level'] = da1['AI impact level'].replace({'High': 'Critical', 'Low': 'Minimal'})

# replace numbers
da1['reskilling_programs_count'] = da1['reskilling_programs_count'].replace(0, np.nan)